### PR TITLE
Remove unecessary commonjs plugin

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Reomove unecessary commonjs plugin

- It is already included automatically by vite and was actually creating conflicts

### CODE REVIEW

**Comment by alexandrebodin** [comment]
So currently this can't be merged.

- Removing it fixes some of the frontend issues but breaks the BE

**Comment by alexandrebodin** [comment]
linked to https://github.com/strapi/pack-up/pull/15

**Comment by alexandrebodin** [comment]
It's ready for review will update the versions once @jhoward1994 has confirmed

**Comment by jhoward1994** [comment]
Tested with the SEO plugin migration with experimental 0.0.0-experimental.3ddc4bc338d159d83d4b4e1119dbda5e56f10cf4 and seems to work fine

Was that built from this branch?

**Comment by alexandrebodin** [comment]
yes :)

**Comment by alexandrebodin** [comment]
And based on https://github.com/strapi/pack-up/pull/15

**Review by innerdvations — DISMISSED** [review]
Works for me (just don't forget to update the pack-up dependency once that's released 😆)

**Comment by alexandrebodin** [comment]
Latest experimental `0.0.0-experimental.da1f28f10a1fa5dfe08e81dae5c1f68e7c25b0af`

**Review by innerdvations — APPROVED** [review]
Works for me!

One concern is that now we see `The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.`

Could we pass in the VITE_CJS_IGNORE_WARNING option since it's not something users have to worry about?

**Comment by alexandrebodin** [comment]
🤔 I don't see how this PR would do that at all

**Comment by alexandrebodin** [comment]
issue upstream. will merge and then update the pack-up dep separatly

**Pull request merged**
